### ISSUE TITLE
Compressed Result

### ISSUE THREAD

**Issue by imomin** [biggora/express-useragent#105]
I am storing the output from the result in the database. It gets too big very fast. Is there an option (or can you add one) to get "minified" data eg.

`{
  isBot:false,
  browser: 'Chrome',
  version: '68.0.3440.106',
  os: 'macOS High Sierra',
  platform: 'Apple Mac',
  device: 'desktop' (or mobile, smartTV...),
  deviceType:'Mac' (or iPhone, iPad, Android),
  deviceVendor:'Apple',
  source: '....'
} `

**Comment by knoxcard** [comment]
You can choose which keys you want....


```
var ua = req.useragent,
     ua_data = []
ua_data.push('isBot', ua.isBot)
ua_data.push('browser', ua.browser)
ua_data.push('version', ua.version)
...

console.log(JSON.stringify(ua_data, null, 4))
// save ua_data as an array to your database for easy viewing and processing...
```
