### ISSUE TITLE
Edge Canary for Mac is [also] detected as Chrome

### ISSUE THREAD

**Issue by june50232** [biggora/express-useragent#113]
Edge Canary news release: [Introducing the first Microsoft Edge preview builds for macOS](https://blogs.windows.com/msedgedev/2019/05/20/microsoft-edge-macos-canary-preview/#Bs5QVRjvS3lA6Qbo.97)
[Edge Canary mac official download](https://www.microsoftedgeinsider.com/en-us/download)

```
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3834.0 Safari/537.36 Edg/77.0.207.0
```
Edge Canary is [also] detected as Chrome

**Comment by june50232** [comment]
https://github.com/biggora/express-useragent/issues/103

**Comment by june50232** [comment]
https://github.com/biggora/express-useragent/issues/103

**Comment by mimmi20** [comment]
@june50232 Could you add a useragent?

**Comment by june50232** [comment]
https://github.com/biggora/express-useragent/issues/100

**Comment by june50232** [comment]
@mimmi20 

also windows10 edge
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.140 Safari/537.36 Edge/18.17763

**Comment by SnidelyWhiplash** [comment]
I'm still getting Edge showing up as Chrome on MacOS with this UA: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.129 Safari/537.36 Edg/81.0.416.68`

I believe the PR from #114 is missing a regex change on this line as well --> https://github.com/biggora/express-useragent/blob/master/lib/express-useragent.js#L103

AFAICT, that line ought to also have `edg` as part of the match pattern, same as what was added to `_Versions` in the PR.
