### ISSUE TITLE
`isElectron` showing false when loaded in Electron app

### ISSUE THREAD

**Issue by thomashibbard** [biggora/express-useragent#130]
electron@^8.2.3 
express-useragent@^1.0.13

Steps to reproduce:
1. Set up Electron to serve a webpage over an Express instance
2. Set up some middleware to log the parsed user-agent 
```
  logUserAgent(request: Request, response: Response, next: any) {
    console.log({
      userAgent: useragent.parse(request.headers['user-agent']),
    });
    next();
  }
```
3. `electron .` to start the app

Among the output, find `isElectron: false`.

Also find the `source` string contains electron however:

```
source: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) electron-app/0.0.1 Chrome/80.0.3987.163 Electron/8.2.3 Safari/537.36'
```

**Comment by NicoIGN** [comment]
same problem here 
user-agent:  
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) 
AppleWebKit/537.36 (KHTML, like Gecko) 
Chrome/83.0.4103.64 
Electron/9.0.0 Safari/537.36

user-agent:  {
"isYaBrowser":false,
"isAuthoritative":true,
"isMobile":false,
"isTablet":false,
"isiPad":false,
"isiPod":false,
"isiPhone":false,
"isAndroid":false,
"isBlackberry":false,
"isOpera":false,
"isIE":false,"isEdge":false,
"isIECompatibilityMode":false,
"isSafari":false,
"isFirefox":false,
"isWebkit":false,
"isChrome":true,
"isKonqueror":false,
"isOmniWeb":false,
"isSeaMonkey":false,
"isFlock":false,
"isAmaya":false,
"isPhantomJS":false,
"isEpiphany":false,
"isDesktop":true,
"isWindows":false,
"isLinux":false,
"isLinux64":false,
"isMac":true,
"isChromeOS":false,
"isBada":false,
"isSamsung":false,
"isRaspberry":false,
"isBot":false,"isCurl":false,
"isAndroidTablet":false,
"isWinJs":false,
"isKindleFire":false,
"isSilk":false,
"isCaptive":false,
"isSmartTV":false,
"isUC":false,
"isFacebook":false,
"isAlamoFire":false,
"isElectron":false,
"silkAccelerated":false,
"browser":"Chrome",
"version":"83.0.4103.64",
"os":"macOS High Sierra",
"platform":"Apple Mac",
"geoIp":{},
"source":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.64 Electron/9.0.0 Safari/537.36"
}
