### ISSUE TITLE
0.1.8 is a breaking API change.  This breaks libraries that use ~ or ^ semver.

### ISSUE THREAD

**Issue by tommymessbauer** [biggora/express-useragent#41]
v.0.1.8 changed the API by returning a different model.  There are at least changes to the following properties
- "Version" is now "version"
- "Browser" is now "browser"

Looks like @JasonDias pointed this out here-
https://github.com/biggora/express-useragent/commit/e3a7db2c7104798569f150403b2fea2fa959c650
### Fix

Based on semver, v0.1.8 should have updated major version b/c this changes the API.
http://semver.org/

There are 2 recommendations to fix:
#### 1. Bump version
- npm unpublish 0.1.8
- increment package version to 1.0.0
- npm publish 1.0.0
### 2. Fix API
- npm unpublish 0.1.8
- make the API compatible
- npm publish 0.1.9
### Repro

Create index.js with this in it.

```
var useragent = require('express-useragent');
var assert = require('assert');

var source = 'Mozilla/5.0 (compatible; MSIE 9.0; Windows NT 6.1; Trident/5.0)',
    ua = useragent.parse(source);

assert.ok(ua.Browser);
console.log('compatible');
```

Now run this to see that the interface parsed and returned "Browser" in 0.1.7 (and every other 0.1.x version)

```
npm i express-useragent@0.1.7
iojs index.js
```

Now do this.  This test fails because "Browser" was renamed to "browser"

```
npm i express-useragent@0.1.8
iojs index.js
```

**Comment by blimmer** [comment]
You wouldn't have to (and probably shouldn't) upgrade to 1.0.0 because that means that you're releasing the public API and have to support it. Per the semver documentation:
```
Major version zero (0.y.z) is for initial development. Anything may change at any time. The public API should not be considered stable.
```

However, this should probably be re-released as `0.2.0` so `^0.1` doesn't auto upgrade.

**Comment by tommymessbauer** [comment]
@blimmer - That makes sense too.  The auto-upgrade was the problem.  0.2.x or 1.0.0 are both good options.

@biggora - I forgot to say this earlier, but thank you for making this module.

**Comment by devjunkORG** [comment]
Did any of this ever get solved?

**Comment by blimmer** [comment]
Nope - seems like radio silence here. Looks like you need to change the casing of Version and Browser to fix it.

**Comment by biggora** [comment]
Yes, you need to change the casing of Version and Browser to fix it.
