### ISSUE TITLE
Add support for Microsoft Edge browser

### ISSUE THREAD

**Issue by nickdima** [biggora/express-useragent#43]
This are the user agents:

Desktop:

`Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.71 Safari/537.36 Edge/12.0`

Mobile:

`Mozilla/5.0 (Windows Phone 10.0; Android 4.2.1; DEVICE INFO) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.71 Mobile Safari/537.36 Edge/12.0`

**Comment by dahei** [comment]
+1

**Comment by FlashJunior** [comment]
+1

@nickdima on my win 10 (desktop) it shows:
`Mozilla/5.0 (Windows NT 10.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.135 Safari/537.36 Edge/12.10240`
