### ISSUE TITLE
Differentiate between OSX versions

### ISSUE THREAD

**Issue by vichle** [biggora/express-useragent#51]
Hi,

I think it's weird that the library does not differentiate between different OSX versions, when it does with Windows versions. I might get to it myself at some point but I don't really have time for it at this point in time, so if anyone else would like to give it a go, please do :)

Best regards,
Viktor

**Comment by Jakobud** [comment]
I'm curious why you would want to differentiate between OSX versions.

**Comment by vichle** [comment]
I'm building a survey system for a major research institute.  They want to have a lot of usage stats, the more the better.  Also, why not?

**Comment by Jakobud** [comment]
Looking at the User Agent on OSX it does contain the version number:

`Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.71 Safari/537.36 `

`10_10_3` = `10.10.3`. So it would definitely be possible to extract. At the same time though, where would you put it? In a new `ua.osVersion` array? Would it contain windows version as well? 2000, Vista, 7, 8, 8.1, 10? What about Linux OS versions? Should it also contain different Linux distro names as well? I dunno what the best approach would be.

**Comment by vichle** [comment]
I guess that a breaking change might be needed to make the API consistent. Either move the windows versions into a new osVersion field and put OSX versions and possibly Linux distribution in there as well, or add the OSX version number at the end of the os string like the windows versions are handled today.

**Comment by Jakobud** [comment]
All of this being said, if you would like to track OSX versions it would be pretty easy to parse the value yourself

```
if (ua.isOsx()) { 
  // parse osx version number from ua
}
```

**Comment by vichle** [comment]
That is true, but I think it makes sense to include it in the library as well. But I guess that's up to you :) I might make a pull request some day in the future when I have some extra time on my hands.

**Comment by Jakobud** [comment]
It's not up to me. Not my library :-) I'm just commenting.

**Comment by vichle** [comment]
Oops, my mistake :)
