### ISSUE TITLE
recognize PhantomJS

### ISSUE THREAD

**Issue by emilioplatzer** [biggora/express-useragent#54]
[PhantomJS](http://phantomjs.org/) is not a real browser, but is a very usefull "testing navigator" for de NodeJS community. 

I use PhantomJS with Mocha and Karma. When I call `new UserAgent().parse( 'Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/534.34 (KHTML, like Gecko) PhantomJS/1.9.8 Safari/534.34' )` I expect to obtain `'PhantomJS 1.9'` (or `'PhantomJS 1.9.8'`)  but I get `'Safari undefined'` (result.browser+' '+result.version)

Could you include this?

Thanks.

**Comment by biggora** [comment]
added

**Comment by emilioplatzer** [comment]
Thanks!
