### ISSUE TITLE
More bots needed

### ISSUE THREAD

**Issue by angelcustodio** [biggora/express-useragent#63]
I've made a PR to update the bots with some additions.
Right now, bots from Google like Page Speed Insights or Validation Sites, Pinterest, Alexa and some others, are not taken as bots so the package cannot identify them properly.

This is the PR where I've implemented several of new bots and tested a weird one like the Page Speed Insight bot.
https://github.com/biggora/express-useragent/pull/62

**Comment by eranbetzalel** [comment]
Your change have been merged, I think you should close this issue.
